# Generated by Django 5.1.1 on 2024-09-29 20:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('zipcode', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('city', models.CharField(max_length=20, verbose_name='شهر')),
                ('country', models.CharField(max_length=20, verbose_name='کشور')),
                ('password', models.CharField(max_length=20, verbose_name='رمز عبور')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام منو')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='آدرس منو')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'منوها',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام آیتم منو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('available', models.BooleanField(default=True, verbose_name='موجود')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.menu', verbose_name='منو')),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'آیتم\u200cهای منو',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره تلفن')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='تاریخ')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='مشتری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.menuitem', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ('-date',),
            },
        ),
    ]
