# Generated by Django 5.1.1 on 2024-10-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_menu_item'),
        ('shop', '0002_discountcode_cart_product_cartitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
